config/routes.rb
ProjectDamager::Application.routes.draw do

  resources :users do
    resources :projects
  end

  root :to => "statics#index"
end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks
  accepts_nested_attributes_for :tasks, :allow_destroy => true
  
  attr_accessible :name, :tasks_attributes
  
  
end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project

  attr_accessible :name

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :projects
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    @current_user ||= User.find(params[:user_id])
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def edit
    @project = current_user.projects.find(params[:id])
    @project.tasks
  end
  
  def update
    @project = current_user.projects.find(params[:id])  
    @project.update_attributes params[:project]
    
    redirect_to edit_user_project_path(current_user, @project)
  end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  
  layout nil
  
  def index
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectDamager</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<h1>ProjectDamager</h1>
<p>Hello, <%= @current_user.username %></p>

<hr/>

<%= yield %>

</body>
</html>

app/views/projects/edit.html.erb
<%= form_for @project, :url => user_project_path do |project_form| %>
  <div>
    <%= project_form.label :name, 'Project name:' %>
    <%= project_form.text_field :name %>
  </div>

  <!-- Here we call fields_for on the project_form builder instance.
       The block is called for each member of the tasks collection. -->
  <%= project_form.fields_for :tasks do |task_form| %>
      <p>
        <div>
          <%= task_form.label :name, 'Task:' %>
          <%= task_form.text_field :name %>
        </div>

        <% unless task_form.object.new_record? %>
          <div>
            <%= task_form.label :_destroy, 'Remove:' %>
            <%= task_form.check_box :_destroy %>
          </div>
        <% end %>
      </p>
  <% end %>

  <%= project_form.submit %>
<% end %>

app/views/statics/index.html.erb
<%= link_to edit_user_project_path(1,1), edit_user_project_path(1,1) %><br/>
<%= link_to edit_user_project_path(2,2), edit_user_project_path(2,2) %>